
// A large list of biology terms. Case-insensitive matching will be applied.
// This list is illustrative and can be expanded significantly.

export const BIOLOGY_TERMS: string[] = [
    "Abiotic factor",
    "Absorption",
    "Acid",
    "Acquired trait",
    "Active transport",
    "Adaptation",
    "Adenine",
    "Adenosine triphosphate (ATP)",
    "Adhesion",
    "Adipose tissue",
    "Adrenal gland",
    "Aerobic respiration",
    "Asexual reproduction",
    "Algae",
    "Allele",
    "Allergy",
    "Alternation of generations",
    "Alveoli",
    "Amino acid",
    "Amniotic egg",
    "Amphibian",
    "Anaerobic respiration",
    "Anaphase",
    "Anatomy",
    "Angiosperm",
    "Animalia",
    "Annelida",
    "Anther",
    "Antibiotic",
    "Antibody",
    "Anticodon",
    "Antigen",
    "Aorta",
    "Apical dominance",
    "Apoptosis",
    "Arachnid",
    "Archaea",
    "Artery",
    "Arthropoda",
    "Asexual reproduction",
    "Atom",
    "ATP",
    "Atrium",
    "Autotroph",
    "Auxin",
    "Axon",
    "Bacteria",
    "Bacteriophage",
    "Base",
    "Behavior",
    "Bilateral symmetry",
    "Binary fission",
    "Binomial nomenclature",
    "Biochemistry",
    "Biodiversity",
    "Biogenesis",
    "Biogeochemical cycle",
    "Biological magnification",
    "Biology",
    "Biomass",
    "Biome",
    "Biosphere",
    "Biotechnology",
    "Biotic factor",
    "Bird",
    "Blastula",
    "Blood",
    "Blood pressure",
    "Blood type",
    "Blood vessel",
    "Bone",
    "Botany",
    "Brain",
    "Bronchi",
    "Bryophyte",
    "Budding",
    "Buffer",
    "Calorie",
    "Calvin cycle",
    "Cambium",
    "Camouflage",
    "Cancer",
    "Capillary",
    "Capsid",
    "Carbohydrate",
    "Carbon cycle",
    "Carcinogen",
    "Cardiac muscle",
    "Carnivore",
    "Carrying capacity",
    "Cartilage",
    "Catalyst",
    "Cell",
    "Cell cycle",
    "Cell differentiation",
    "Cell division",
    "Cell membrane",
    "Cell plate",
    "Cell respiration",
    "Cell theory",
    "Cell wall",
    "Cellular respiration",
    "Cellulose",
    "Central nervous system",
    "Centriole",
    "Centromere",
    "Cerebellum",
    "Cerebrum",
    "Chemical bond",
    "Chemiosmosis",
    "Chemosynthesis",
    "Chitin",
    "Chlorophyll",
    "Chloroplast",
    "Cholesterol",
    "Chordata",
    "Chromatid",
    "Chromatin",
    "Chromosome",
    "Cilia",
    "Circadian rhythm",
    "Circulatory system",
    "Cladogram",
    "Class",
    "Classification",
    "Cleavage",
    "Climate",
    "Climax community",
    "Cloning",
    "Cnidaria",
    "Codominance",
    "Codon",
    "Coelom",
    "Coenzyme",
    "Cohesion",
    "Commensalism",
    "Community",
    "Companion cell",
    "Competition",
    "Complementary base pairing",
    "Compound",
    "Concentration gradient",
    "Condensation",
    "Conditioning",
    "Cone (plant)",
    "Cone (eye)",
    "Conifer",
    "Conjugation",
    "Connective tissue",
    "Conservation",
    "Consumer",
    "Contractile vacuole",
    "Control group",
    "Convergent evolution",
    "Coral",
    "Cork cambium",
    "Corolla",
    "Corpus luteum",
    "Cortex",
    "Cotyledon",
    "Covalent bond",
    "Cranium",
    "Krebs cycle", // Often searched as Krebs cycle
    "Crossing over",
    "Crustacean",
    "Cuticle",
    "Cyanobacteria",
    "Cytokinesis",
    "Cytoplasm",
    "Cytosine",
    "Cytoskeleton",
    "Cytosol",
    "Deciduous",
    "Decomposer",
    "Deforestation",
    "Dehydration synthesis",
    "Deletion",
    "Denaturation",
    "Dendrite",
    "Density-dependent factor",
    "Density-independent factor",
    "Deoxyribonucleic acid (DNA)",
    "Deoxyribose",
    "Dependent variable",
    "Dermis",
    "Desert",
    "Detritivore",
    "Development",
    "Diabetes",
    "Diaphragm",
    "Diastole",
    "Diatom",
    "Dicot",
    "Diffusion",
    "Digestion",
    "Digestive system",
    "Dihybrid cross",
    "Diploid",
    "Directional selection",
    "Disaccharide",
    "Disruptive selection",
    "Divergent evolution",
    "DNA",
    "DNA fingerprinting",
    "DNA ligase",
    "DNA polymerase",
    "DNA replication",
    "Dominant allele",
    "Dormancy",
    "Dorsal",
    "Double fertilization",
    "Double helix",
    "Down syndrome",
    "Duodenum",
    "Echinodermata",
    "Ecological pyramid",
    "Ecological succession",
    "Ecology",
    "Ecosystem",
    "Ectoderm",
    "Ectotherm",
    "Egg",
    "Electron",
    "Electron transport chain",
    "Element",
    "Embryo",
    "Embryology",
    "Emigration",
    "Endangered species",
    "Endocrine gland",
    "Endocrine system",
    "Endocytosis",
    "Endoderm",
    "Endoplasmic reticulum",
    "Endoskeleton",
    "Endosperm",
    "Endospore",
    "Endosymbiosis",
    "Endotherm",
    "Endotoxin",
    "Energy",
    "Energy pyramid",
    "Entropy",
    "Environment",
    "Enzyme",
    "Epidermis",
    "Epigenetics",
    "Epiglottis",
    "Epinephrine",
    "Epithelial tissue",
    "Equilibrium",
    "Erosion",
    "Esophagus",
    "Estivation",
    "Estrogen",
    "Estuary",
    "Ethology",
    "Ethylene",
    "Eubacteria",
    "Eukaryote",
    "Eutrophication",
    "Evaporation",
    "Evolution",
    "Excretion",
    "Excretory system",
    "Exergonic reaction",
    "Exocrine gland",
    "Exocytosis",
    "Exon",
    "Exoskeleton",
    "Exotoxin",
    "Experiment",
    "Exponential growth",
    "Extinction",
    "Extracellular digestion",
    "Eye",
    "F1 generation",
    "F2 generation",
    "Facilitated diffusion",
    "FAD",
    "Family",
    "Fat",
    "Fatty acid",
    "Fauna",
    "Feedback inhibition",
    "Fermentation",
    "Fern",
    "Fertilization",
    "Fetus",
    "Fibrin",
    "Fibrous root",
    "Filament",
    "Filter feeder",
    "Fin",
    "Fish",
    "Flagellum",
    "Flower",
    "Fluid mosaic model",
    "Follicle",
    "Food chain",
    "Food web",
    "Fossil",
    "Founder effect",
    "Frameshift mutation",
    "Frond",
    "Fruit",
    "Fungi",
    "Gallbladder",
    "Gamete",
    "Gametophyte",
    "Ganglion",
    "Gas exchange",
    "Gastrula",
    "Gene",
    "Gene expression",
    "Gene flow",
    "Gene frequency",
    "Gene pool",
    "Gene therapy",
    "Genetic code",
    "Genetic drift",
    "Genetic engineering",
    "Genetic equilibrium",
    "Genetic marker",
    "Genetic recombination",
    "Genetics",
    "Genome",
    "Genotype",
    "Genus",
    "Geographic isolation",
    "Germ layer",
    "Germination",
    "Gestation",
    "Gibberellin",
    "Gill",
    "Gizzard",
    "Global warming",
    "Glomerulus",
    "Glucagon",
    "Glucose",
    "Glycerol",
    "Glycogen",
    "Glycolysis",
    "Golgi apparatus",
    "Gonad",
    "Gradualism",
    "Grana",
    "Grassland",
    "Gravitropism",
    "Greenhouse effect",
    "Growth",
    "Growth hormone",
    "Guanine",
    "Guard cell",
    "Gymnosperm",
    "Habitat",
    "Habituation",
    "Haploid",
    "Hardy-Weinberg principle",
    "Heart",
    "Heart rate",
    "Helper T cell",
    "Hemoglobin",
    "Herbivore",
    "Heredity",
    "Hermaphrodite",
    "Heterotroph",
    "Heterozygous",
    "Hibernation",
    "Histamine",
    "Histone",
    "HIV",
    "Homeostasis",
    "Homeotic gene",
    "Hominid",
    "Homologous chromosome",
    "Homologous structure",
    "Homozygous",
    "Hormone",
    "Host",
    "Human Genome Project",
    "Hybrid",
    "Hydrogen bond",
    "Hydrolysis",
    "Hydrophilic",
    "Hydrophobic",
    "Hydrostatic skeleton",
    "Hypothalamus",
    "Hypothesis",
    "Immune system",
    "Immunity",
    "Imprinting",
    "Inbreeding",
    "Incomplete dominance",
    "Independent assortment",
    "Independent variable",
    "Indicator species",
    "Inertia",
    "Inflammation",
    "Inheritance",
    "Innate behavior",
    "Insect",
    "Insertion",
    "Instinct",
    "Insulin",
    "Integumentary system",
    "Interferon",
    "Interneuron",
    "Interphase",
    "Interspecific competition",
    "Intertidal zone",
    "Intestine",
    "Intraspecific competition",
    "Intron",
    "Invertebrate",
    "Ion",
    "Ionic bond",
    "Isotope",
    "Jacobson's organ",
    "Jejunum",
    "Joint",
    "Karyotype",
    "Keratin",
    "Keystone species",
    "Kidney",
    "Kin selection",
    "Kinesis",
    "Kingdom",
    "Klinefelter syndrome",
    "Krebs cycle",
    "Lactic acid fermentation",
    "Larva",
    "Larynx",
    "Lateral line",
    "Law of independent assortment",
    "Law of segregation",
    "Leaf",
    "Learning",
    "Lenticel",
    "Lichen",
    "Life cycle",
    "Ligament",
    "Light reaction",
    "Limiting factor",
    "Linkage group",
    "Lipid",
    "Littoral zone",
    "Liver",
    "Logistic growth",
    "Lung",
    "Lymph",
    "Lymphatic system",
    "Lymphocyte",
    "Lysogenic cycle",
    "Lysosome",
    "Lytic cycle",
    "Macromolecule",
    "Macrophage",
    "Malpighian tubule",
    "Mammal",
    "Mandible",
    "Marine biome",
    "Marsupial",
    "Mass",
    "Mass extinction",
    "Matter",
    "Medulla oblongata",
    "Medusa",
    "Meiosis",
    "Melanin",
    "Melatonin",
    "Memory cell",
    "Mendelian genetics",
    "Menstrual cycle",
    "Meristem",
    "Mesoderm",
    "Mesophyll",
    "Messenger RNA (mRNA)",
    "Metabolism",
    "Metamorphosis",
    "Metaphase",
    "Metastasis",
    "Microbiology",
    "Microfilament",
    "Microscope",
    "Microtubule",
    "Migration",
    "Mimicry",
    "Mineral",
    "Mitochondrion",
    "Mitosis",
    "Molecule",
    "Mollusca",
    "Molting",
    "Monocot",
    "Monohybrid cross",
    "Monosaccharide",
    "Monotreme",
    "Morphogenesis",
    "Moss",
    "Motor neuron",
    "mRNA",
    "Mucus",
    "Multiple alleles",
    "Muscle",
    "Muscle tissue",
    "Mutagen",
    "Mutation",
    "Mutualism",
    "Mycelium",
    "Mycorrhiza",
    "Myelin sheath",
    "Myofibril",
    "Myosin",
    "NAD",
    "NADP",
    "Natural selection",
    "Neanderthal",
    "Nematoda",
    "Nephridium",
    "Nephron",
    "Nerve",
    "Nerve impulse",
    "Nervous system",
    "Nervous tissue",
    "Neuron",
    "Neurotransmitter",
    "Neutron",
    "Niche",
    "Nitrogen cycle",
    "Nitrogen fixation",
    "Nitrogenous base",
    "Node of Ranvier",
    "Nondisjunction",
    "Nonrenewable resource",
    "Notochord",
    "Nuclear envelope",
    "Nuclear pore",
    "Nucleic acid",
    "Nucleoid",
    "Nucleolus",
    "Nucleotide",
    "Nucleus",
    "Nutrient",
    "Nutrition",
    "Nymph",
    "Olfactory bulb",
    "Omnivore",
    "Oogenesis",
    "Operant conditioning",
    "Operon",
    "Optic nerve",
    "Order",
    "Organ",
    "Organ system",
    "Organelle",
    "Organic compound",
    "Organism",
    "Osmosis",
    "Osmoregulation",
    "Osteocyte",
    "Ovary",
    "Oviduct",
    "Ovulation",
    "Ovule",
    "Ovum",
    "Oxidation",
    "Oxygen",
    "Ozone layer",
    "Paleontology",
    "Pancreas",
    "Parasite",
    "Parasitism",
    "Parasympathetic nervous system",
    "Parathyroid gland",
    "Parenchyma",
    "Parthenogenesis",
    "Passive transport",
    "Pathogen",
    "Pedigree",
    "Pelvic girdle",
    "Penis",
    "Pepsin",
    "Peptide bond",
    "Perennial",
    "Pericycle",
    "Peripheral nervous system",
    "Peristalsis",
    "Petal",
    "Petiole",
    "pH",
    "Phagocytosis",
    "Pharynx",
    "Phenotype",
    "Pheromone",
    "Phloem",
    "Phosphate group",
    "Phospholipid",
    "Phosphorus cycle",
    "Photoperiodism",
    "Photosynthesis",
    "Photosystem",
    "Phototropism",
    "Phylum",
    "Physiology",
    "Phytochrome",
    "Phytoplankton",
    "Pigment",
    "Pineal gland",
    "Pinocytosis",
    "Pioneer species",
    "Pistil",
    "Pith",
    "Pituitary gland",
    "Placenta",
    "Plankton",
    "Plant",
    "Plantae",
    "Plasma",
    "Plasma cell",
    "Plasma membrane",
    "Plasmid",
    "Plasmodium",
    "Plasmolysis",
    "Platelet",
    "Platyhelminthes",
    "Point mutation",
    "Polar body",
    "Polar molecule",
    "Pollen",
    "Pollination",
    "Polygenic inheritance",
    "Polymer",
    "Polymerase chain reaction (PCR)",
    "Polyp",
    "Polypeptide",
    "Polyploidy",
    "Polysaccharide",
    "Pons",
    "Population",
    "Population density",
    "Population genetics",
    "Porifera",
    "Posterior",
    "Predation",
    "Predator",
    "Prey",
    "Primary consumer",
    "Primary growth",
    "Primary structure",
    "Primary succession",
    "Primate",
    "Primer",
    "Prion",
    "Producer",
    "Product",
    "Progesterone",
    "Prokaryote",
    "Prolactin",
    "Promoter",
    "Prophase",
    "Prostate gland",
    "Protein",
    "Protista",
    "Proton",
    "Protozoa",
    "Provirus",
    "Pseudopod",
    "Puberty",
    "Pulmonary artery",
    "Pulmonary circulation",
    "Pulmonary vein",
    "Punctuated equilibrium",
    "Punnett square",
    "Pupa",
    "Pupil",
    "Purine",
    "Pyloric sphincter",
    "Pyrimidine",
    "Quaternary structure",
    "Radial symmetry",
    "Radicle",
    "Radioactive dating",
    "Rain forest",
    "Reactant",
    "Receptor",
    "Recessive allele",
    "Recombinant DNA",
    "Rectum",
    "Red blood cell",
    "Reduction",
    "Reflex",
    "Regeneration",
    "Regulatory gene",
    "Renewable resource",
    "Replication",
    "Reproduction",
    "Reproductive isolation",
    "Reproductive system",
    "Reptile",
    "Respiration",
    "Respiratory system",
    "Restriction enzyme",
    "Retina",
    "Retrovirus",
    "Rhizoid",
    "Rhizome",
    "Ribonucleic acid (RNA)",
    "Ribose",
    "Ribosomal RNA (rRNA)",
    "Ribosome",
    "RNA",
    "RNA polymerase",
    "Rod (eye)",
    "Root",
    "Root cap",
    "Root hair",
    "Rough ER",
    "rRNA",
    "Rubisco",
    "Rumen",
    "Sac fungi",
    "Saliva",
    "Salivary gland",
    "Saprophyte",
    "Sarcomere",
    "Saturated fat",
    "Savanna",
    "Scale (fish)",
    "Scavenger",
    "Sclerenchyma",
    "Scrotum",
    "Secondary consumer",
    "Secondary growth",
    "Secondary structure",
    "Secondary succession",
    "Seed",
    "Seed coat",
    "Segregation",
    "Selective breeding",
    "Semen",
    "Semicircular canals",
    "Seminal vesicle",
    "Seminiferous tubule",
    "Sensory neuron",
    "Sepal",
    "Sessile",
    "Sex chromosome",
    "Sex linkage",
    "Sex-linked trait",
    "Sexual reproduction",
    "Sexual selection",
    "Shoot",
    "Short-day plant",
    "Sieve tube element",
    "Simple leaf",
    "Sinoatrial node",
    "Skeletal muscle",
    "Skeletal system",
    "Skin",
    "Skull",
    "Small intestine",
    "Smooth ER",
    "Smooth muscle",
    "Sodium-potassium pump",
    "Solution",
    "Solvent",
    "Somatic cell",
    "Somatic nervous system",
    "Sorus",
    "Speciation",
    "Species",
    "Specific heat",
    "Sperm",
    "Spermatogenesis",
    "Sphincter",
    "Spicule",
    "Spinal cord",
    "Spindle fiber",
    "Spiracle",
    "Spleen",
    "Sponge",
    "Spontaneous generation",
    "Sporangium",
    "Spore",
    "Sporophyte",
    "Stabilizing selection",
    "Stamen",
    "Starch",
    "Stem",
    "Stem cell",
    "Steroid",
    "Stigma",
    "Stimulus",
    "Stomach",
    "Stomata",
    "Stroma",
    "Style",
    "Substrate",
    "Succession",
    "Sucrose",
    "Sugar",
    "Surface tension",
    "Survivorship curve",
    "Suspension feeder",
    "Sustainable development",
    "Swim bladder",
    "Symbiosis",
    "Sympathetic nervous system",
    "Synapse",
    "Synapsis",
    "Systematics",
    "Systemic circulation",
    "Systole",
    "Taiga",
    "Taproot",
    "Target cell",
    "Taste bud",
    "Taxis",
    "Taxonomy",
    "Telomere",
    "Telophase",
    "Temperate forest",
    "Temperature",
    "Tendon",
    "Territoriality",
    "Tertiary consumer",
    "Tertiary structure",
    "Test cross",
    "Testis",
    "Testosterone",
    "Tetrad",
    "Thalamus",
    "Theory",
    "Thermodynamics",
    "Thigmotropism",
    "Thorax",
    "Thrombin",
    "Thylakoid",
    "Thymine",
    "Thymus",
    "Thyroid gland",
    "Tissue",
    "Tolerance",
    "Trachea",
    "Tracheid",
    "Trait",
    "Transcription",
    "Transduction",
    "Transfer RNA (tRNA)",
    "Transformation",
    "Translation",
    "Translocation",
    "Transmission electron microscope",
    "Transpiration",
    "Transport protein",
    "Transposon",
    "Trial-and-error learning",
    "Triglyceride",
    "tRNA",
    "Trophic level",
    "Tropical rain forest",
    "Tropism",
    "Trypsin",
    "Tube foot",
    "Tuber",
    "Tumor",
    "Tundra",
    "Turner syndrome",
    "Umbilical cord",
    "Ungulate",
    "Unicellular",
    "Unsaturated fat",
    "Uracil",
    "Urea",
    "Ureter",
    "Urethra",
    "Uric acid",
    "Urinary bladder",
    "Urinary system",
    "Urine",
    "Uterus",
    "Vaccine",
    "Vacuole",
    "Vagina",
    "Variable",
    "Variation",
    "Vascular bundle",
    "Vascular cambium",
    "Vascular cylinder",
    "Vascular plant",
    "Vascular tissue",
    "Vector",
    "Vegetative propagation",
    "Vein",
    "Vena cava",
    "Ventral",
    "Ventricle",
    "Vertebra",
    "Vertebrate",
    "Vessel element",
    "Vestigial structure",
    "Villi",
    "Virus",
    "Vitamin",
    "Water cycle",
    "Water vascular system",
    "Wax",
    "Wetland",
    "White blood cell",
    "X chromosome",
    "Xerophyte",
    "Xylem",
    "Y chromosome",
    "Yeast",
    "Yolk sac",
    "Zoology",
    "Zooplankton",
    "Zygospore",
    "Zygote"
];
