
// A large list of biology terms. Case-insensitive matching will be applied.
// This list is illustrative and can be expanded significantly.

export const BIOLOGY_TERMS: string[] = [
    "Abiotic factor",
    "Absorption",
    "Acid",
    "Acquired trait",
    "Active transport",
    "Adaptation",
    "Adaptive radiation",
    "Adenine",
    "Adenosine triphosphate (ATP)",
    "Adhesion",
    "Adipose tissue",
    "Adrenal gland",
    "Aerobic respiration",
    "Asexual reproduction",
    "Agar",
    "AIDS (Acquired Immunodeficiency Syndrome)",
    "Albumin",
    "Alcoholic fermentation",
    "Algae",
    "Allele",
    "Allergy",
    "Allopatric speciation",
    "Alternation of generations",
    "Alveoli",
    "Amino acid",
    "Ammonia",
    "Amniotic egg",
    "Amniotic fluid",
    "Amoeba",
    "Amphibian",
    "Amylase",
    "Anaerobic respiration",
    "Analogous structure",
    "Anaphase",
    "Anatomy",
    "Angiosperm",
    "Animalia",
    "Annelida",
    "Anther",
    "Antibiotic",
    "Antibody",
    "Anticodon",
    "Antigen",
    "Aorta",
    "Apical dominance",
    "Apical meristem",
    "Apoptosis",
    "Arachnid",
    "Archaea",
    "Artery",
    "Arthropoda",
    "Asexual reproduction",
    "Atom",
    "ATP",
    "Atrium",
    "Autonomic nervous system",
    "Autosome",
    "Autotroph",
    "Auxin",
    "Axon",
    "Bacteria",
    "Bacteriophage",
    "Basal metabolic rate",
    "Base",
    "Behavior",
    "Bilateral symmetry",
    "Bile",
    "Binary fission",
    "Binomial nomenclature",
    "Biochemistry",
    "Biodegradable",
    "Biodiversity",
    "Biogenesis",
    "Biogeochemical cycle",
    "Biological clock",
    "Biological magnification",
    "Biology",
    "Biomass",
    "Biome",
    "Biosphere",
    "Biotechnology",
    "Biotic factor",
    "Bipedalism",
    "Bird",
    "Bivalve",
    "Blastocyst",
    "Blastula",
    "Blood",
    "Blood pressure",
    "Blood type",
    "Blood vessel",
    "Bone",
    "Bone marrow",
    "Botany",
    "Brain",
    "Brainstem",
    "Bronchi",
    "Bronchiole",
    "Bryophyte",
    "Budding",
    "Buffer",
    "Calorie",
    "Calvin cycle",
    "Calyx",
    "Cambium",
    "Camouflage",
    "Cancer",
    "Capillary",
    "Capsid",
    "Capsule",
    "Carbohydrate",
    "Carbon cycle",
    "Carbon fixation",
    "Carcinogen",
    "Cardiac muscle",
    "Carnivore",
    "Carotenoid",
    "Carpel",
    "Carrying capacity",
    "Cartilage",
    "Catalyst",
    "Cell",
    "Cell cycle",
    "Cell differentiation",
    "Cell division",
    "Cell junction",
    "Cell membrane",
    "Cell plate",
    "Cell respiration",
    "Cell theory",
    "Cell wall",
    "Cellular respiration",
    "Cellulose",
    "Central nervous system",
    "Centriole",
    "Centromere",
    "Cephalization",
    "Cerebellum",
    "Cerebral cortex",
    "Cerebrum",
    "Cervix",
    "Chemical bond",
    "Chemical energy",
    "Chemical reaction",
    "Chemiosmosis",
    "Chemoreceptor",
    "Chemosynthesis",
    "Chitin",
    "Chlorophyll",
    "Chloroplast",
    "Cholesterol",
    "Chordata",
    "Chromatid",
    "Chromatin",
    "Chromosome",
    "Chromosome map",
    "Cilia",
    "Circadian rhythm",
    "Circulatory system",
    "Cladistics",
    "Cladogram",
    "Class",
    "Classification",
    "Cleavage",
    "Climate",
    "Climax community",
    "Cloaca",
    "Cloning",
    "Cnidaria",
    "Codominance",
    "Codon",
    "Coelom",
    "Coenzyme",
    "Coevolution",
    "Cohesion",
    "Cohesion-tension theory",
    "Coleoptile",
    "Collagen",
    "Collenchyma",
    "Colon",
    "Colony",
    "Commensalism",
    "Community",
    "Companion cell",
    "Competition",
    "Complement system",
    "Complementary base pairing",
    "Compound",
    "Compound eye",
    "Compound leaf",
    "Concentration gradient",
    "Condensation",
    "Conditioning",
    "Cone (plant)",
    "Cone (eye)",
    "Conifer",
    "Conjugation",
    "Connective tissue",
    "Conservation",
    "Consumer",
    "Contractile vacuole",
    "Control group",
    "Convergent evolution",
    "Coral",
    "Cork cambium",
    "Cornea",
    "Corolla",
    "Corpus luteum",
    "Cortex",
    "Cotyledon",
    "Covalent bond",
    "Cranium",
    "Krebs cycle", // Often searched as Krebs cycle
    "Crop",
    "Crossing over",
    "Crustacean",
    "Cuticle",
    "Cyanobacteria",
    "Cyclic AMP (cAMP)",
    "Cytokinesis",
    "Cytokinin",
    "Cytoplasm",
    "Cytosine",
    "Cytoskeleton",
    "Cytosol",
    "Cytotoxic T cell",
    "Darwinism",
    "Deciduous",
    "Decomposer",
    "Deforestation",
    "Dehydration synthesis",
    "Deletion",
    "Denaturation",
    "Dendrite",
    "Denitrification",
    "Density-dependent factor",
    "Density-independent factor",
    "Deoxyribonucleic acid (DNA)",
    "Deoxyribose",
    "Dependent variable",
    "Dermal tissue",
    "Dermis",
    "Desert",
    "Detritivore",
    "Deuterostome",
    "Development",
    "Diabetes",
    "Diaphragm",
    "Diastole",
    "Diatom",
    "Dicot",
    "Diffusion",
    "Digestion",
    "Digestive system",
    "Dihybrid cross",
    "Diploid",
    "Directional selection",
    "Disaccharide",
    "Disruptive selection",
    "Divergent evolution",
    "DNA",
    "DNA fingerprinting",
    "DNA ligase",
    "DNA polymerase",
    "DNA replication",
    "Dominant allele",
    "Dominant species",
    "Dormancy",
    "Dorsal",
    "Double fertilization",
    "Double helix",
    "Down syndrome",
    "Duodenum",
    "Echinodermata",
    "Ecological niche",
    "Ecological pyramid",
    "Ecological succession",
    "Ecology",
    "Ecosystem",
    "Ectoderm",
    "Ectotherm",
    "Effector cell",
    "Egg",
    "Electron",
    "Electron microscope",
    "Electron transport chain",
    "Element",
    "Embryo",
    "Embryology",
    "Embryo sac",
    "Emigration",
    "Endangered species",
    "Endemic species",
    "Endergonic reaction",
    "Endocrine gland",
    "Endocrine system",
    "Endocytosis",
    "Endoderm",
    "Endodermis",
    "Endometrium",
    "Endoplasmic reticulum",
    "Endoskeleton",
    "Endosperm",
    "Endospore",
    "Endosymbiosis",
    "Endotherm",
    "Endotoxin",
    "Energy",
    "Energy pyramid",
    "Entropy",
    "Environment",
    "Enzyme",
    "Epidermis",
    "Epididymis",
    "Epigenetics",
    "Epiglottis",
    "Epinephrine",
    "Epiphyte",
    "Epithelial tissue",
    "Epoch",
    "Equilibrium",
    "Era",
    "Erosion",
    "Esophagus",
    "Essential amino acid",
    "Estivation",
    "Estrogen",
    "Estuary",
    "Ethology",
    "Ethylene",
    "Eubacteria",
    "Euglena",
    "Eukaryote",
    "Eusocial",
    "Eutrophication",
    "Evaporation",
    "Evolution",
    "Excretion",
    "Excretory system",
    "Exergonic reaction",
    "Exocrine gland",
    "Exocytosis",
    "Exon",
    "Exoskeleton",
    "Exotic species",
    "Exotoxin",
    "Experiment",
    "Exponential growth",
    "Extensor",
    "Extinction",
    "Extracellular digestion",
    "Extracellular matrix",
    "Eye",
    "Eyespot",
    "F1 generation",
    "F2 generation",
    "Facilitated diffusion",
    "FAD",
    "Fallopian tube",
    "Family",
    "Fat",
    "Fatty acid",
    "Fauna",
    "Feedback inhibition",
    "Feedback loop",
    "Femur",
    "Fermentation",
    "Fern",
    "Fertilization",
    "Fetus",
    "Fibrin",
    "Fibrinogen",
    "Fibrous root",
    "Filament",
    "Filter feeder",
    "Fin",
    "First law of thermodynamics",
    "Fish",
    "Fission",
    "Fitness",
    "Fixed action pattern",
    "Flagellum",
    "Flexor",
    "Flower",
    "Fluid mosaic model",
    "Follicle",
    "Food chain",
    "Food web",
    "Fossil",
    "Fossil fuel",
    "Founder effect",
    "Frameshift mutation",
    "Frond",
    "Fruit",
    "FSH (Follicle-stimulating hormone)",
    "Fungi",
    "Gallbladder",
    "Gamete",
    "Gametogenesis",
    "Gametophyte",
    "Ganglion",
    "Gas exchange",
    "Gastric juice",
    "Gastrula",
    "Gastrulation",
    "Gel electrophoresis",
    "Gene",
    "Gene expression",
    "Gene flow",
    "Gene frequency",
    "Gene mapping",
    "Gene pool",
    "Gene regulation",
    "Gene therapy",
    "Genetic code",
    "Genetic counseling",
    "Genetic drift",
    "Genetic engineering",
    "Genetic equilibrium",
    "Genetic marker",
    "Genetic recombination",
    "Genetics",
    "Genome",
    "Genomic library",
    "Genotype",
    "Genus",
    "Geographic isolation",
    "Geotropism",
    "Germ layer",
    "Germination",
    "Gestation",
    "Gibberellin",
    "Gill",
    "Gizzard",
    "Gland",
    "Global warming",
    "Glomerulus",
    "Glucagon",
    "Glucose",
    "Glycerol",
    "Glycogen",
    "Glycolysis",
    "Glycoprotein",
    "Golgi apparatus",
    "Gonad",
    "Gradualism",
    "Gram stain",
    "Grana",
    "Grassland",
    "Gravitropism",
    "Greenhouse effect",
    "Ground tissue",
    "Growth",
    "Growth curve",
    "Growth factor",
    "Growth hormone",
    "Guanine",
    "Guard cell",
    "Guttation",
    "Gymnosperm",
    "Habitat",
    "Habitat fragmentation",
    "Habituation",
    "Hair follicle",
    "Half-life",
    "Haploid",
    "Hardy-Weinberg principle",
    "Haversian canal",
    "Heart",
    "Heart rate",
    "Heartwood",
    "Heat",
    "Helper T cell",
    "Hemoglobin",
    "Hemophilia",
    "Herbivore",
    "Heredity",
    "Hermaphrodite",
    "Heterotroph",
    "Heterozygous",
    "Hibernation",
    "Histamine",
    "Histone",
    "HIV",
    "Homeobox",
    "Homeostasis",
    "Homeotic gene",
    "Hominid",
    "Homologous chromosome",
    "Homologous structure",
    "Homozygous",
    "Hormone",
    "Host",
    "Human Genome Project",
    "Humerus",
    "Humoral immunity",
    "Humus",
    "Huntington's disease",
    "Hybrid",
    "Hybridization",
    "Hydrogen bond",
    "Hydrolysis",
    "Hydrophilic",
    "Hydrophobic",
    "Hydroponics",
    "Hydrostatic skeleton",
    "Hydrothermal vent",
    "Hypertonic",
    "Hyphae",
    "Hypocotyl",
    "Hypothalamus",
    "Hypothesis",
    "Hypotonic",
    "Ileum",
    "Immune response",
    "Immune system",
    "Immunity",
    "Immunodeficiency",
    "Implantation",
    "Imprinting",
    "In vitro fertilization",
    "Inbreeding",
    "Incomplete dominance",
    "Incomplete metamorphosis",
    "Independent assortment",
    "Independent variable",
    "Indicator species",
    "Indigenous species",
    "Induced fit",
    "Inflammation",
    "Ingestion",
    "Inheritance",
    "Innate behavior",
    "Inner ear",
    "Insect",
    "Insertion",
    "Insight learning",
    "Instinct",
    "Insulin",
    "Integumentary system",
    "Interferon",
    "Interleukin",
    "Intermediate filament",
    "Interneuron",
    "Internode",
    "Interphase",
    "Interspecific competition",
    "Interstitial fluid",
    "Intertidal zone",
    "Intestine",
    "Intracellular digestion",
    "Intraspecific competition",
    "Introduced species",
    "Intron",
    "Invasive species",
    "Inversion",
    "Invertebrate",
    "Ion",
    "Ionic bond",
    "Iris",
    "Irritability",
    "Islets of Langerhans",
    "Isotonic",
    "Isotope",
    "Jacobson's organ",
    "Jejunum",
    "Joint",
    "Jungle",
    "Karyotype",
    "Keratin",
    "Keystone species",
    "Kidney",
    "Kin selection",
    "Kinesis",
    "Kinetic energy",
    "Kinetochore",
    "Kingdom",
    "Klinefelter syndrome",
    "Krebs cycle",
    "Lactic acid fermentation",
    "Lactation",
    "Lactose",
    "Lagging strand",
    "Lamella",
    "Lamprey",
    "Lancelet",
    "Large intestine",
    "Larva",
    "Larynx",
    "Lateral line",
    "Lateral meristem",
    "Law of independent assortment",
    "Law of segregation",
    "Leading strand",
    "Leaf",
    "Learning",
    "Lectin",
    "Leech",
    "Lens",
    "Lenticel",
    "Leukocyte",
    "LH (Luteinizing hormone)",
    "Lichen",
    "Life cycle",
    "Ligament",
    "Ligase",
    "Light reaction",
    "Lignin",
    "Limiting factor",
    "Linkage",
    "Linkage group",
    "Linnaeus",
    "Lipase",
    "Lipid",
    "Littoral zone",
    "Liver",
    "Locus",
    "Logistic growth",
    "Long-day plant",
    "Loop of Henle",
    "Lung",
    "Lymph",
    "Lymph node",
    "Lymphatic system",
    "Lymphocyte",
    "Lysogenic cycle",
    "Lysosome",
    "Lytic cycle",
    "Macroevolution",
    "Macromolecule",
    "Macrophage",
    "Madreporite",
    "Malpighian tubule",
    "Mammal",
    "Mandible",
    "Mantle",
    "Marine biome",
    "Marsupial",
    "Mass",
    "Mass extinction",
    "Mast cell",
    "Matter",
    "Maxilla",
    "Mechanoreceptor",
    "Medulla oblongata",
    "Medusa",
    "Megaspore",
    "Meiosis",
    "Melanin",
    "Melatonin",
    "Membrane potential",
    "Memory cell",
    "Mendel, Gregor",
    "Mendelian genetics",
    "Meninges",
    "Menstrual cycle",
    "Meristem",
    "Mesoderm",
    "Mesoglea",
    "Mesophyll",
    "Mesozoic Era",
    "Messenger RNA (mRNA)",
    "Metabolism",
    "Metamorphosis",
    "Metaphase",
    "Metastasis",
    "Microbiology",
    "Microevolution",
    "Microfilament",
    "Micrograph",
    "Micropyle",
    "Microscope",
    "Microspore",
    "Microtubule",
    "Microvilli",
    "Midbrain",
    "Middle ear",
    "Middle lamella",
    "Migration",
    "Mimicry",
    "Mineral",
    "Mitochondrion",
    "Mitosis",
    "Mole",
    "Molecular biology",
    "Molecular clock",
    "Molecule",
    "Mollusca",
    "Molting",
    "Monocot",
    "Monocyte",
    "Monohybrid cross",
    "Monomer",
    "Monosaccharide",
    "Monotreme",
    "Morphogenesis",
    "Morphology",
    "Mortality",
    "Morula",
    "Mosaic evolution",
    "Moss",
    "Motor neuron",
    "Motor unit",
    "mRNA",
    "Mucus",
    "Müllerian mimicry",
    "Multicellular",
    "Multiple alleles",
    "Muscle",
    "Muscle tissue",
    "Mutagen",
    "Mutation",
    "Mutualism",
    "Mycelium",
    "Mycology",
    "Mycorrhiza",
    "Myelin sheath",
    "Myofibril",
    "Myoglobin",
    "Myosin",
    "NAD",
    "NADH",
    "NADP",
    "NADPH",
    "Natality",
    "Natural killer cell",
    "Natural selection",
    "Neanderthal",
    "Nectary",
    "Nematocyst",
    "Nematoda",
    "Nephridium",
    "Nephron",
    "Nerve",
    "Nerve cord",
    "Nerve impulse",
    "Nerve net",
    "Nervous system",
    "Nervous tissue",
    "Neuron",
    "Neurosecretory cell",
    "Neurotransmitter",
    "Neutron",
    "Neutrophil",
    "Niche",
    "Nitrogen cycle",
    "Nitrogen fixation",
    "Nitrogenous base",
    "Nocturnal",
    "Node",
    "Node of Ranvier",
    "Nodule",
    "Non-Mendelian inheritance",
    "Nondisjunction",
    "Nonpolar molecule",
    "Nonrenewable resource",
    "Notochord",
    "Nuclear envelope",
    "Nuclear pore",
    "Nuclease",
    "Nucleic acid",
    "Nucleoid",
    "Nucleolus",
    "Nucleosome",
    "Nucleotide",
    "Nucleus",
    "Nutrient",
    "Nutrient cycle",
    "Nutrition",
    "Nymph",
    "Obligate aerobe",
    "Obligate anaerobe",
    "Oceanic zone",
    "Ocelli",
    "Olfactory bulb",
    "Oligosaccharide",
    "Omnivore",
    "Oncogene",
    "Oogenesis",
    "Operant conditioning",
    "Operator",
    "Operon",
    "Optic nerve",
    "Oral groove",
    "Order",
    "Organ",
    "Organ system",
    "Organelle",
    "Organic compound",
    "Organism",
    "Osmoconformer",
    "Osmoregulation",
    "Osmoregulator",
    "Osmosis",
    "Ossification",
    "Osteoblast",
    "Osteoclast",
    "Osteocyte",
    "Ostracoderm",
    "Otolith",
    "Outer ear",
    "Ovary",
    "Oviduct",
    "Oviparous",
    "Ovoviviparous",
    "Ovulation",
    "Ovule",
    "Ovum",
    "Oxidation",
    "Oxidative phosphorylation",
    "Oxygen",
    "Oxyhemoglobin",
    "Oxytocin",
    "Ozone layer",
    "P generation",
    "Pacemaker",
    "Paleontology",
    "Paleozoic Era",
    "Palisade mesophyll",
    "Pancreas",
    "Pangaea",
    "Papilla",
    "Paramecium",
    "Parasite",
    "Parasitism",
    "Parasympathetic nervous system",
    "Parathyroid gland",
    "Parathyroid hormone (PTH)",
    "Parenchyma",
    "Parthenogenesis",
    "Passive transport",
    "Pathogen",
    "PCR (Polymerase chain reaction)",
    "Pectoral girdle",
    "Pedigree",
    "Pelagic zone",
    "Pellicle",
    "Pelvic girdle",
    "Penis",
    "Pepsin",
    "Pepsinogen",
    "Peptide bond",
    "Perennial",
    "Pericycle",
    "Periosteum",
    "Peripheral nervous system",
    "Peristalsis",
    "Permafrost",
    "Peroxisome",
    "Petal",
    "Petiole",
    "pH",
    "Phage",
    "Phagocyte",
    "Phagocytosis",
    "Pharyngeal pouch",
    "Pharynx",
    "Phenotype",
    "Pheromone",
    "Phloem",
    "Phosphate group",
    "Phospholipid",
    "Phospholipid bilayer",
    "Phosphorus cycle",
    "Phosphorylation",
    "Photic zone",
    "Photoautotroph",
    "Photoperiodism",
    "Photophosphorylation",
    "Photoreceptor",
    "Photorespiration",
    "Photosynthesis",
    "Photosystem",
    "Phototropism",
    "pH scale",
    "Phycobilin",
    "Phylogenetic tree",
    "Phylogeny",
    "Phylum",
    "Physiology",
    "Phytochrome",
    "Phytoplankton",
    "Pigment",
    "Pili",
    "Pineal gland",
    "Pinocytosis",
    "Pioneer species",
    "Pistil",
    "Pith",
    "Pituitary gland",
    "Placenta",
    "Placoderm",
    "Planaria",
    "Plankton",
    "Plant",
    "Plantae",
    "Plasma",
    "Plasma cell",
    "Plasma membrane",
    "Plasmid",
    "Plasmodesmata",
    "Plasmodium",
    "Plasmolysis",
    "Plastid",
    "Plate tectonics",
    "Platelet",
    "Platyhelminthes",
    "Pleura",
    "Plumule",
    "Point mutation",
    "Polar body",
    "Polar molecule",
    "Polar nuclei",
    "Pollen",
    "Pollen grain",
    "Pollen tube",
    "Pollination",
    "Pollution",
    "Polygenic inheritance",
    "Polymer",
    "Polymerase chain reaction (PCR)",
    "Polymorphism",
    "Polyp",
    "Polypeptide",
    "Polyploidy",
    "Polysaccharide",
    "Pons",
    "Population",
    "Population density",
    "Population dispersion",
    "Population genetics",
    "Porifera",
    "Portal system",
    "Posterior",
    "Potential energy",
    "Prairie",
    "Precambrian Era",
    "Precipitation",
    "Predation",
    "Predator",
    "Prehensile tail",
    "Pressure-flow hypothesis",
    "Prey",
    "Primary consumer",
    "Primary growth",
    "Primary productivity",
    "Primary structure",
    "Primary succession",
    "Primate",
    "Primer",
    "Prion",
    "Probability",
    "Proboscis",
    "Producer",
    "Product",
    "Progesterone",
    "Proglottid",
    "Prokaryote",
    "Prolactin",
    "Promoter",
    "Prophase",
    "Prostaglandin",
    "Prostate gland",
    "Protein",
    "Protein synthesis",
    "Prothrombin",
    "Protista",
    "Proton",
    "Proton pump",
    "Protonephridium",
    "Protostome",
    "Protozoa",
    "Provirus",
    "Pseudocoelom",
    "Pseudopod",
    "Puberty",
    "Pulmonary artery",
    "Pulmonary circulation",
    "Pulmonary vein",
    "Punctuated equilibrium",
    "Punnett square",
    "Pupa",
    "Pupil",
    "Purine",
    "Pyloric sphincter",
    "Pyramid of biomass",
    "Pyramid of energy",
    "Pyramid of numbers",
    "Pyrimidine",
    "Pyruvic acid",
    "Quadrat",
    "Quaternary structure",
    "Radial symmetry",
    "Radiation",
    "Radicle",
    "Radioactive dating",
    "Radioisotope",
    "Radula",
    "Rain forest",
    "Random sampling",
    "Reactant",
    "Receptor",
    "Receptor protein",
    "Recessive allele",
    "Recombinant DNA",
    "Recombination frequency",
    "Rectum",
    "Red blood cell",
    "Red tide",
    "Redox reaction",
    "Reduction",
    "Reflex",
    "Reflex arc",
    "Regeneration",
    "Regulatory gene",
    "Release factor",
    "Releasing hormone",
    "Renal artery",
    "Renal vein",
    "Renewable resource",
    "Replication",
    "Replication fork",
    "Repressible operon",
    "Repressor",
    "Reproduction",
    "Reproductive isolation",
    "Reproductive system",
    "Reptile",
    "Residue",
    "Resource partitioning",
    "Respiration",
    "Respiratory system",
    "Resting potential",
    "Restriction enzyme",
    "Restriction map",
    "Reticular formation",
    "Retina",
    "Retrovirus",
    "Reverse transcriptase",
    "Rh factor",
    "Rhizoid",
    "Rhizome",
    "Rhodopsin",
    "Ribonucleic acid (RNA)",
    "Ribose",
    "Ribosomal RNA (rRNA)",
    "Ribosome",
    "Ribozyme",
    "RNA",
    "RNA interference (RNAi)",
    "RNA polymerase",
    "RNA processing",
    "Rod (eye)",
    "Root",
    "Root cap",
    "Root hair",
    "Root nodule",
    "Root pressure",
    "Rough ER",
    "Roundworm",
    "rRNA",
    "Rubisco",
    "Rumen",
    "Ruminant",
    "Sac fungi",
    "Saliva",
    "Salivary gland",
    "Salt gland",
    "Sampling",
    "Sap",
    "Saprobe",
    "Saprophyte",
    "Sapwood",
    "Sarcomere",
    "Sarcoplasmic reticulum",
    "Saturated fat",
    "Savanna",
    "Scale (fish)",
    "Scanning electron microscope",
    "Scavenger",
    "Schwann cell",
    "Scientific method",
    "Scientific name",
    "Sclera",
    "Sclereid",
    "Sclerenchyma",
    "Scolex",
    "Scrotum",
    "Second law of thermodynamics",
    "Second messenger",
    "Secondary consumer",
    "Secondary growth",
    "Secondary structure",
    "Secondary succession",
    "Secretin",
    "Secretion",
    "Seed",
    "Seed coat",
    "Seed dispersal",
    "Seedling",
    "Segment",
    "Segmentation",
    "Segregation",
    "Selective breeding",
    "Selective permeability",
    "Semen",
    "Semicircular canals",
    "Semilunar valve",
    "Seminal receptacle",
    "Seminal vesicle",
    "Seminiferous tubule",
    "Sense organ",
    "Sensory adaptation",
    "Sensory neuron",
    "Sensory receptor",
    "Sepal",
    "Septum",
    "Sessile",
    "Seta",
    "Sex chromosome",
    "Sex determination",
    "Sex linkage",
    "Sex-influenced trait",
    "Sex-limited trait",
    "Sex-linked trait",
    "Sexual dimorphism",
    "Sexual reproduction",
    "Sexual selection",
    "Shoot",
    "Short-day plant",
    "Sickle cell anemia",
    "Sieve plate",
    "Sieve tube element",
    "Signal transduction pathway",
    "Simple leaf",
    "Sinoatrial node",
    "Sinus",
    "Siphon",
    "Skeletal muscle",
    "Skeletal system",
    "Skin",
    "Skull",
    "Sliding filament model",
    "Small intestine",
    "Smooth ER",
    "Smooth muscle",
    "Sodium-potassium pump",
    "Soil",
    "Solute",
    "Solution",
    "Solvent",
    "Somatic cell",
    "Somatic nervous system",
    "Somite",
    "Sorus",
    "Speciation",
    "Species",
    "Species diversity",
    "Specific heat",
    "Spectrophotometer",
    "Sperm",
    "Spermatid",
    "Spermatocyte",
    "Spermatogenesis",
    "Sphincter",
    "Spicule",
    "Spinal cord",
    "Spindle",
    "Spindle fiber",
    "Spine",
    "Spiracle",
    "Spleen",
    "Sponge",
    "Spongy mesophyll",
    "Spontaneous generation",
    "Sporangium",
    "Spore",
    "Sporophyte",
    "Sporozoan",
    "Spring tide",
    "Stabilizing selection",
    "Stamen",
    "Starch",
    "Stem",
    "Stem cell",
    "Steroid",
    "Sterol",
    "Sticky end",
    "Stigma",
    "Stimulant",
    "Stimulus",
    "Stolon",
    "Stomach",
    "Stomata",
    "Stop codon",
    "Stratified squamous epithelium",
    "Streptococcus",
    "Striation",
    "Stroke",
    "Stroma",
    "Stromatolite",
    "Style",
    "Subcutaneous layer",
    "Suberin",
    "Subspecies",
    "Substrate",
    "Substrate-level phosphorylation",
    "Succession",
    "Sucrose",
    "Sugar",
    "Sulfur cycle",
    "Superior vena cava",
    "Surface tension",
    "Survivorship curve",
    "Suspension feeder",
    "Sustainable agriculture",
    "Sustainable development",
    "Suture",
    "Sweat gland",
    "Swim bladder",
    "Symbiont",
    "Symbiosis",
    "Sympathetic nervous system",
    "Sympatric speciation",
    "Synapse",
    "Synapsis",
    "Synaptic cleft",
    "Synaptic terminal",
    "Synaptic vesicle",
    "Synovial fluid",
    "Syphilis",
    "Systematics",
    "Systemic circulation",
    "Systole",
    "T cell",
    "Taiga",
    "Tail",
    "Taproot",
    "Target cell",
    "Taste bud",
    "Taxis",
    "Taxon",
    "Taxonomy",
    "Technology",
    "Tectorial membrane",
    "Telomere",
    "Telophase",
    "Telson",
    "Temperate deciduous forest",
    "Temperate forest",
    "Temperate grassland",
    "Temperature",
    "Template strand",
    "Temporal isolation",
    "Tendon",
    "Tentacle",
    "Terminal bud",
    "Territoriality",
    "Tertiary consumer",
    "Tertiary structure",
    "Test cross",
    "Testis",
    "Testosterone",
    "Tetrad",
    "Tetrapod",
    "Thalamus",
    "Thallus",
    "Theory",
    "Thermodynamics",
    "Thermophile",
    "Thermoreceptor",
    "Thermoregulation",
    "Thigmotropism",
    "Thoracic cavity",
    "Thorax",
    "Thorn",
    "Threatened species",
    "Thrombin",
    "Thrombocyte",
    "Thylakoid",
    "Thymine",
    "Thymus",
    "Thyroid gland",
    "Thyroxine",
    "Tidal volume",
    "Tight junction",
    "Tissue",
    "Tolerance",
    "Tonsil",
    "Topoisomerase",
    "Torpor",
    "Torsion",
    "Touch receptor",
    "Trachea",
    "Tracheae",
    "Tracheid",
    "Trait",
    "Transcription",
    "Transcription factor",
    "Transduction",
    "Transfer RNA (tRNA)",
    "Transformation",
    "Transgenic organism",
    "Translation",
    "Translocation",
    "Transmission electron microscope",
    "Transpiration",
    "Transport protein",
    "Transposon",
    "Trial-and-error learning",
    "Tricarboxylic acid cycle",
    "Triglyceride",
    "Trilobite",
    "Triploid",
    "Trisomy",
    "tRNA",
    "Trochophore",
    "Trophic level",
    "Tropical rain forest",
    "Tropism",
    "Tropomyosin",
    "Troponin",
    "Trypsin",
    "Trypsinogen",
    "Tube foot",
    "Tuber",
    "Tubulin",
    "Tumor",
    "Tumor suppressor gene",
    "Tundra",
    "Tunicate",
    "Turbellaria",
    "Turgor pressure",
    "Turner syndrome",
    "Twins",
    "Tympanic membrane",
    "Typhlosole",
    "Ulcer",
    "Ulna",
    "Ultrafiltration",
    "Ultrasonic",
    "Ultrasound",
    "Ultraviolet radiation",
    "Umbilical cord",
    "Ungulate",
    "Unicellular",
    "Uniformitarianism",
    "Uniramous appendage",
    "Unsaturated fat",
    "Upwelling",
    "Uracil",
    "Urea",
    "Ureter",
    "Urethra",
    "Uric acid",
    "Urinary bladder",
    "Urinary system",
    "Urine",
    "Urochordata",
    "Uterus",
    "Utricle",
    "Vaccination",
    "Vaccine",
    "Vacuole",
    "Vagina",
    "Valence electron",
    "Valve",
    "Variable",
    "Variation",
    "Variety",
    "Vascular bundle",
    "Vascular cambium",
    "Vascular cylinder",
    "Vascular plant",
    "Vascular tissue",
    "Vas deferens",
    "Vasoconstriction",
    "Vasodilation",
    "Vector",
    "Vegetal pole",
    "Vegetative propagation",
    "Vein",
    "Vena cava",
    "Ventilation",
    "Ventral",
    "Ventricle",
    "Venule",
    "Vertebra",
    "Vertebral column",
    "Vertebrate",
    "Vessel element",
    "Vestigial structure",
    "Villi",
    "Virus",
    "Viscera",
    "Visceral mass",
    "Visible light",
    "Vitamin",
    "Vitreous humor",
    "Viviparous",
    "Vocal cord",
    "Volcano",
    "Volume",
    "Voluntary muscle",
    "Volvox",
    "Vulva",
    "Wallace, Alfred Russel",
    "Warning coloration",
    "Water cycle",
    "Water potential",
    "Water vascular system",
    "Watson and Crick",
    "Wax",
    "Weather",
    "Weathering",
    "Weed",
    "Wetland",
    "Whale",
    "White blood cell",
    "Wildlife",
    "Windpipe",
    "Wing",
    "Wood",
    "X chromosome",
    "Xanthophyll",
    "Xerophyte",
    "Xylem",
    "Y chromosome",
    "Yeast",
    "Yolk",
    "Yolk sac",
    "Z line",
    "Zoology",
    "Zooplankton",
    "Zoospore",
    "Zygomycota",
    "Zygospore",
    "Zygote"
];
