

// A large list of biology terms. Case-insensitive matching will be applied.
// This list is illustrative and can be expanded significantly.

export const BIOLOGY_TERMS: string[] = [
    // Core Biology Concepts
    "Abiotic factor",
    "Absorption",
    "Acid",
    "Acquired trait",
    "Active transport",
    "Adaptation",
    "Adaptive radiation",
    "Adenine",
    "Adenosine triphosphate (ATP)",
    "Adhesion",
    "Aerobic respiration",
    "Asexual reproduction",
    "Allele",
    "Amino acid",
    "Anaerobic respiration",
    "Anatomy",
    "Animalia",
    "Antibiotic",
    "Antibody",
    "Antigen",
    "Apoptosis",
    "Atom",
    "ATP",
    "Autotroph",
    "Auxin",
    "Base",
    "Behavior",
    "Binary fission",
    "Binomial nomenclature",
    "Biochemistry",
    "Biodiversity",
    "Biogenesis",
    "Biogeochemical cycle",
    "Biology",
    "Biomass",
    "Biome",
    "Biosphere",
    "Biotechnology",
    "Biotic factor",
    "Botany",
    "Buffer",
    "Calorie",
    "Calvin cycle",
    "Carbohydrate",
    "Carbon cycle",
    "Carbon fixation",
    "Carnivore",
    "Catalyst",
    "Cell",
    "Cell cycle",
    "Cell differentiation",
    "Cell division",
    "Cell membrane",
    "Cell respiration",
    "Cell theory",
    "Cell wall",
    "Cellular respiration",
    "Cellulose",
    "Chemical bond",
    "Chemical energy",
    "Chemical reaction",
    "Chemosynthesis",
    "Chitin",
    "Chlorophyll",
    "Chloroplast",
    "Cholesterol",
    "Chordata",
    "Chromatid",
    "Chromatin",
    "Chromosome",
    "Classification",
    "Climax community",
    "Cloning",
    "Codominance",
    "Codon",
    "Coevolution",
    "Cohesion",
    "Commensalism",
    "Community",
    "Competition",
    "Compound",
    "Concentration gradient",
    "Condensation",
    "Conservation",
    "Consumer",
    "Convergent evolution",
    "Covalent bond",
    "Crossing over",
    "Cytokinesis",
    "Cytoplasm",
    "Cytosine",
    "Cytoskeleton",
    "Cytosol",
    "Decomposer",
    "Dehydration synthesis",
    "Deletion",
    "Denaturation",
    "Density-dependent factor",
    "Density-independent factor",
    "Deoxyribonucleic acid (DNA)",
    "Deoxyribose",
    "Dependent variable",
    "Diffusion",
    "Digestion",
    "Diploid",
    "Directional selection",
    "Disruptive selection",
    "Divergent evolution",
    "DNA",
    "DNA replication",
    "Dominant allele",
    "Double helix",
    "Ecology",
    "Ecosystem",
    "Electron",
    "Element",
    "Embryo",
    "Endangered species",
    "Endemic species",
    "Endosymbiosis",
    "Energy",
    "Entropy",
    "Environment",
    "Enzyme",
    "Eukaryote",
    "Evolution",
    "Excretion",
    "Exergonic reaction",
    "Experiment",
    "Exponential growth",
    "Extinction",
    "Facilitated diffusion",
    "Fat",
    "Fatty acid",
    "Feedback inhibition",
    "Fermentation",
    "Fertilization",
    "Fitness",
    "Food chain",
    "Food web",
    "Fossil",
    "Gene",
    "Gene expression",
    "Gene flow",
    "Gene pool",
    "Gene regulation",
    "Genetic code",
    "Genetic drift",
    "Genetic engineering",
    "Genetic equilibrium",
    "Genetics",
    "Genome",
    "Genotype",
    "Genus",
    "Global warming",
    "Glucose",
    "Glycolysis",
    "Golgi apparatus",
    "Greenhouse effect",
    "Growth",
    "Guanine",
    "Habitat",
    "Half-life",
    "Haploid",
    "Hardy-Weinberg principle",
    "Herbivore",
    "Heredity",
    "Heterotroph",
    "Heterozygous",
    "Homeostasis",
    "Homologous structure",
    "Homozygous",
    "Hormone",
    "Host",
    "Hydrogen bond",
    "Hydrolysis",
    "Hydrophilic",
    "Hydrophobic",
    "Hypothesis",
    "Immunity",
    "Inbreeding",
    "Incomplete dominance",
    "Independent assortment",
    "Independent variable",
    "Inheritance",
    "Interphase",
    "Intron",
    "Ion",
    "Ionic bond",
    "Isotope",
    "Karyotype",
    "Keystone species",
    "Kingdom",
    "Krebs cycle",
    "Law of independent assortment",
    "Law of segregation",
    "Life cycle",
    "Limiting factor",
    "Lipid",
    "Logistic growth",
    "Lysosome",
    "Macroevolution",
    "Macromolecule",
    "Mass extinction",
    "Meiosis",
    "Metabolism",
    "Metamorphosis",
    "Metaphase",
    "Microevolution",
    "Microscope",
    "Mimicry",
    "Mineral",
    "Mitochondria",
    "Mitochondrion",
    "Mitosis",
    "Molecule",
    "Monohybrid cross",
    "Monomer",
    "Monosaccharide",
    "Mutation",
    "Mutualism",
    "Mycorrhiza",
    "Natural selection",
    "Niche",
    "Nitrogen cycle",
    "Nitrogen fixation",
    "Nitrogenous base",
    "Nondisjunction",
    "Nucleic acid",
    "Nucleoid",
    "Nucleolus",
    "Nucleotide",
    "Nucleus",
    "Nutrient",
    "Nutrient cycle",
    "Nutrition",
    "Omnivore",
    "Organ",
    "Organ system",
    "Organelle",
    "Organic compound",
    "Organism",
    "Osmosis",
    "Oxidation",
    "Parasitism",
    "Passive transport",
    "Pathogen",
    "PCR (Polymerase chain reaction)",
    "Pedigree",
    "pH",
    "Phenotype",
    "Phospholipid",
    "Phospholipid bilayer",
    "Photosynthesis",
    "Phylogeny",
    "Phylum",
    "Physiology",
    "Pigment",
    "Plasma membrane",
    "Plasmid",
    "Plastid",
    "Point mutation",
    "Polar molecule",
    "Polymer",
    "Polysaccharide",
    "Population",
    "Population density",
    "Population genetics",
    "Predation",
    "Primary consumer",
    "Primary productivity",
    "Prokaryote",
    "Prophase",
    "Protein",
    "Protein synthesis",
    "Protista",
    "Proton",
    "Punctuated equilibrium",
    "Punnett square",
    "Purine",
    "Pyrimidine",
    "Recessive allele",
    "Recombinant DNA",
    "Redox reaction",
    "Reduction",
    "Replication",
    "Reproduction",
    "Resource partitioning",
    "Respiration",
    "Restriction enzyme",
    "Retrovirus",
    "Ribonucleic acid (RNA)",
    "Ribose",
    "Ribosome",
    "RNA",
    "RNA polymerase",
    "Scientific method",
    "Secondary consumer",
    "Seed",
    "Segregation",
    "Selective permeability",
    "Sex chromosome",
    "Sex linkage",
    "Sexual reproduction",
    "Sexual selection",
    "Species",
    "Speciation",
    "Spontaneous generation",
    "Spore",
    "Stabilizing selection",
    "Starch",
    "Stem cell",
    "Steroid",
    "Stimulus",
    "Stomata",
    "Substrate",
    "Succession",
    "Symbiosis",
    "Taxon",
    "Taxonomy",
    "Telophase",
    "Temperature",
    "Territoriality",
    "Tertiary consumer",
    "Test cross",
    "Theory",
    "Thylakoid",
    "Thymine",
    "Tissue",
    "Trait",
    "Transcription",
    "Transfer RNA (tRNA)",
    "Transformation",
    "Transgenic organism",
    "Translation",
    "Transpiration",
    "Trophic level",
    "Uracil",
    "Vacuole",
    "Variation",
    "Vascular plant",
    "Vascular tissue",
    "Vector",
    "Vertebrate",
    "Vestigial structure",
    "Virus",
    "Vitamin",
    "Water cycle",
    "X chromosome",
    "Xylem",
    "Y chromosome",
    "Zoology",
    "Zygote",

    // Human Anatomy & Physiology
    "Abdomen",
    "Acetylcholine",
    "Actin",
    "Adrenal gland",
    "Adrenaline", // Epinephrine
    "Alveolus", // Plural Alveoli
    "Amniotic fluid",
    "Ankle",
    "Antibody",
    "Aorta",
    "Appendix",
    "Arm",
    "Artery",
    "Atrium",
    "Axon",
    "Backbone", // Vertebral column
    "Bile",
    "Bladder", // Urinary bladder
    "Blood",
    "Blood pressure",
    "Blood vessel",
    "Bone",
    "Bone marrow",
    "Brain",
    "Brainstem",
    "Bronchus", // Plural Bronchi
    "Capillary",
    "Cardiac muscle",
    "Cartilage",
    "Cell membrane",
    "Cerebellum",
    "Cerebrum",
    "Cervix",
    "Cheek",
    "Chest",
    "Chin",
    "Circulatory system",
    "Clavicle", // Collarbone
    "Colon", // Large intestine part
    "Connective tissue",
    "Cornea",
    "Cranium", // Skull
    "Dendrite",
    "Dermis",
    "Diaphragm",
    "Digestive system",
    "Duodenum",
    "Ear",
    "Eardrum", // Tympanic membrane
    "Elbow",
    "Endocrine system",
    "Epidermis",
    "Epiglottis",
    "Epinephrine",
    "Esophagus",
    "Estrogen",
    "Eye",
    "Eyebrow",
    "Eyelash",
    "Eyelid",
    "Face",
    "Fallopian tube",
    "Femur", // Thigh bone
    "Fetus",
    "Fibula",
    "Finger",
    "Fingernail",
    "Foot",
    "Forehead",
    "Gallbladder",
    "Gamete",
    "Gastrointestinal tract",
    "Gland",
    "Glucagon",
    "Hair",
    "Hair follicle",
    "Hand",
    "Head",
    "Heart",
    "Heel",
    "Hemoglobin",
    "Hip",
    "Humerus",
    "Immune system",
    "Insulin",
    "Intestine", // Small intestine, Large intestine
    "Iris",
    "Jaw",
    "Joint",
    "Kidney",
    "Knee",
    "Large intestine",
    "Larynx", // Voice box
    "Leg",
    "Lens (eye)",
    "Ligament",
    "Lip",
    "Liver",
    "Lung",
    "Lymph",
    "Lymph node",
    "Lymphatic system",
    "Mandible", // Lower jaw
    "Marrow", // Bone marrow
    "Maxilla", // Upper jaw
    "Melanin",
    "Menstrual cycle",
    "Mouth",
    "Muscle",
    "Muscle tissue",
    "Myelin sheath",
    "Myosin",
    "Nail", // Fingernail, Toenail
    "Navel", // Umbilicus
    "Neck",
    "Nephron",
    "Nerve",
    "Nervous system",
    "Neuron",
    "Neurotransmitter",
    "Nose",
    "Nostril",
    "Ovary",
    "Ovum", // Egg cell
    "Pancreas",
    "Patella", // Kneecap
    "Pelvis",
    "Penis",
    "Peripheral nervous system",
    "Pharynx",
    "Pituitary gland",
    "Placenta",
    "Plasma",
    "Platelet",
    "Progesterone",
    "Prostate gland",
    "Puberty",
    "Pulse",
    "Pupil",
    "Radius (bone)",
    "Rectum",
    "Red blood cell",
    "Reflex",
    "Reproductive system",
    "Respiratory system",
    "Retina",
    "Rib",
    "Saliva",
    "Salivary gland",
    "Scalp",
    "Scapula", // Shoulder blade
    "Sclera",
    "Scrotum",
    "Semen",
    "Sense organ",
    "Shin",
    "Shoulder",
    "Skeleton",
    "Skeletal muscle",
    "Skin",
    "Skull",
    "Small intestine",
    "Smooth muscle",
    "Sodium-potassium pump",
    "Sperm",
    "Spinal cord",
    "Spleen",
    "Sternum", // Breastbone
    "Stomach",
    "Sweat gland",
    "Synapse",
    "T cell",
    "Tarsals", // Ankle bones
    "Taste bud",
    "Teeth", // Tooth
    "Tendon",
    "Testis", // Plural Testes
    "Testosterone",
    "Thigh",
    "Thorax", // Chest
    "Thumb",
    "Thymus",
    "Thyroid gland",
    "Thyroxine",
    "Tibia", // Shin bone
    "Toe",
    "Toenail",
    "Tongue",
    "Tonsil",
    "Tooth",
    "Trachea", // Windpipe
    "Ulna",
    "Umbilical cord",
    "Ureter",
    "Urethra",
    "Urinary bladder",
    "Urinary system",
    "Urine",
    "Uterus", // Womb
    "Vagina",
    "Vein",
    "Ventricle (heart)",
    "Vertebra", // Plural Vertebrae
    "Vertebral column",
    "Villus", // Plural Villi
    "Voice box", // Larynx
    "Waist",
    "White blood cell",
    "Windpipe", // Trachea
    "Womb", // Uterus
    "Wrist",

    // Animals, Insects, Mammals, Nature
    "Aardvark",
    "Albatross",
    "Alligator",
    "Alpaca",
    "Amphibian",
    "Anemone",
    "Ant",
    "Anteater",
    "Antelope",
    "Ape",
    "Arachnid",
    "Arctic fox",
    "Armadillo",
    "Baboon",
    "Badger",
    "Barnacle",
    "Barracuda",
    "Bat",
    "Bear",
    "Beaver",
    "Bedbug",
    "Bee",
    "Beetle",
    "Bird",
    "Bison",
    "Bluebird",
    "Boa constrictor",
    "Boar",
    "Bobcat",
    "Butterfly",
    "Buzzard",
    "Camel",
    "Canary",
    "Capybara",
    "Cardinal",
    "Caribou",
    "Cat",
    "Caterpillar",
    "Catfish",
    "Cattle",
    "Centipede",
    "Chameleon",
    "Cheetah",
    "Chickadee",
    "Chicken",
    "Chimpanzee",
    "Chinchilla",
    "Chipmunk",
    "Clam",
    "Clownfish",
    "Cobra",
    "Cockroach",
    "Cod",
    "Condor",
    "Coral",
    "Cougar",
    "Cow",
    "Coyote",
    "Crab",
    "Crane",
    "Crawdad", // Crayfish
    "Crayfish",
    "Cricket",
    "Crocodile",
    "Crow",
    "Cuckoo",
    "Curlew",
    "Cuttlefish",
    "Deer",
    "Dingo",
    "Dinosaur",
    "Dog",
    "Dolphin",
    "Donkey",
    "Dove",
    "Dragonfly",
    "Duck",
    "Dugong",
    "Eagle",
    "Earthworm",
    "Echidna",
    "Eel",
    "Egret",
    "Elephant",
    "Elk",
    "Emu",
    "Falcon",
    "Fauna",
    "Ferret",
    "Finch",
    "Firefly",
    "Fish",
    "Flamingo",
    "Flea",
    "Flounder",
    "Fly",
    "Fox",
    "Frog",
    "Fungi",
    "Gazelle",
    "Gecko",
    "Gerbil",
    "Gibbon",
    "Giraffe",
    "Gnat",
    "Gnu", // Wildebeest
    "Goat",
    "Goldfinch",
    "Goldfish",
    "Goose",
    "Gopher",
    "Gorilla",
    "Grasshopper",
    "Grouse",
    "Guanaco",
    "Guinea fowl",
    "Guinea pig",
    "Gull",
    "Guppy",
    "Haddock",
    "Halibut",
    "Hamster",
    "Hare",
    "Hawk",
    "Hedgehog",
    "Heron",
    "Herring",
    "Hippopotamus",
    "Hornet",
    "Horse",
    "Human",
    "Hummingbird",
    "Hyena",
    "Ibex",
    "Ibis",
    "Iguana",
    "Impala",
    "Insect",
    "Jackal",
    "Jaguar",
    "Jay",
    "Jellyfish",
    "Kangaroo",
    "Kingfisher",
    "Koala",
    "Komodo dragon",
    "Kookaburra",
    "Kudu",
    "Ladybug",
    "Lake",
    "Lamprey",
    "Lark",
    "Leech",
    "Lemming",
    "Lemur",
    "Leopard",
    "Liger",
    "Lion",
    "Lizard",
    "Llama",
    "Lobster",
    "Locust",
    "Loris",
    "Louse",
    "Lynx",
    "Lyrebird",
    "Macaw",
    "Mackerel",
    "Magpie",
    "Mallard",
    "Mammal",
    "Manatee",
    "Mandrill",
    "Manta ray",
    "Mantis",
    "Marlin",
    "Marmoset",
    "Marmot",
    "Marsupial",
    "Marten",
    "Meerkat",
    "Mink",
    "Mole",
    "Mollusk",
    "Mongoose",
    "Monkey",
    "Moose",
    "Mosquito",
    "Moth",
    "Mountain",
    "Mouse",
    "Mule",
    "Muskrat",
    "Mussel",
    "Narwhal",
    "Nature",
    "Newt",
    "Nightingale",
    "Octopus",
    "Okapi",
    "Opossum",
    "Orangutan",
    "Orca", // Killer whale
    "Ostrich",
    "Otter",
    "Owl",
    "Ox",
    "Oyster",
    "Panda",
    "Panther",
    "Parakeet",
    "Parrot",
    "Partridge",
    "Peacock",
    "Peafowl",
    "Pelican",
    "Penguin",
    "Perch",
    "Pheasant",
    "Pig",
    "Pigeon",
    "Pike",
    "Plankton",
    "Platypus",
    "Polar bear",
    "Pony",
    "Porcupine",
    "Porpoise",
    "Prairie dog",
    "Prawn",
    "Primate",
    "Puffin",
    "Puma",
    "Python",
    "Quail",
    "Quelea",
    "Quetzal",
    "Quokka",
    "Rabbit",
    "Raccoon",
    "Rail",
    "Ram",
    "Rat",
    "Rattlesnake",
    "Raven",
    "Ray", // Manta ray, Stingray
    "Reindeer",
    "Reptile",
    "Rhinoceros",
    "River",
    "Roadrunner",
    "Robin",
    "Rodent",
    "Rook",
    "Rooster",
    "Salamander",
    "Salmon",
    "Sand dollar",
    "Sandpiper",
    "Sardine",
    "Scallop",
    "Scorpion",
    "Sea lion",
    "Sea urchin",
    "Seahorse",
    "Seal",
    "Shark",
    "Sheep",
    "Shrew",
    "Shrimp",
    "Skunk",
    "Sloth",
    "Snail",
    "Snake",
    "Snipe",
    "Snow leopard",
    "Sole",
    "Sparrow",
    "Spider",
    "Sponge",
    "Squid",
    "Squirrel",
    "Starfish",
    "Starling",
    "Stingray",
    "Stink bug",
    "Stork",
    "Sturgeon",
    "Swallow",
    "Swan",
    "Swordfish",
    "Tahr",
    "Takin",
    "Tamarin",
    "Tapir",
    "Tarantula",
    "Tarsier",
    "Tasmanian devil",
    "Termite",
    "Tern",
    "Thrush",
    "Tick",
    "Tiger",
    "Toad",
    "Tortoise",
    "Toucan",
    "Tree",
    "Trout",
    "Tuna",
    "Turkey",
    "Turtle",
    "Urial",
    "Vicuña",
    "Viper",
    "Vole",
    "Vulture",
    "Wallaby",
    "Walrus",
    "Wasp",
    "Water buffalo",
    "Weasel",
    "Whale",
    "Wildebeest",
    "Wolf",
    "Wolverine",
    "Wombat",
    "Woodcock",
    "Woodpecker",
    "Worm",
    "Wren",
    "Yak",
    "Yellowjacket",
    "Zebra",
    "Zebu",
    "Zonkey",
    "Zorse",

];
